import { Alert, Autocomplete, Button, FormControl, TextField } from '@mui/material';
import React, { useState } from 'react';
import { IFilterSettingTypeProp } from './types';

// all tags available for the user
const tags = ['1980s',
"1990's",
'2.5D',
'2D',
'2D Fighter',
'360 Video',
'3D',
'3D Platformer',
'3D Vision',
'4 Player Local',
'4X',
'6DOF',
'ATV',
'Abstract',
'Action',
'Action RPG',
'Action-Adventure',
'Addictive',
'Adventure',
'Agriculture',
'Aliens',
'Alternate History',
'America',
'Animation & Modeling',
'Anime',
'Arcade',
'Arena Shooter',
'Artificial Intelligence',
'Assassin',
'Asymmetric VR',
'Asynchronous Multiplayer',
'Atmospheric',
'Audio Production',
'Automation',
'BMX',
'Base Building',
'Baseball',
'Based On A Novel',
'Basketball',
'Batman',
'Battle Royale',
"Beat 'em up",
'Beautiful',
'Benchmark',
'Bikes',
'Blood',
'Board Game',
'Bowling',
'Building',
'Bullet Hell',
'Bullet Time',
'CRPG',
'Capitalism',
'Card Game',
'Cartoon',
'Cartoony',
'Casual',
'Cats',
'Character Action Game',
'Character Customization',
'Chess',
'Choices Matter',
'Choose Your Own Adventure',
'Cinematic',
'City Builder',
'Class-Based',
'Classic',
'Clicker',
'Co-op',
'Co-op Campaign',
'Cold War',
'Colorful',
'Comedy',
'Comic Book',
'Competitive',
'Conspiracy',
'Controller',
'Conversation',
'Crafting',
'Crime',
'Crowdfunded',
'Cult Classic',
'Cute',
'Cyberpunk',
'Cycling',
'Dark',
'Dark Comedy',
'Dark Fantasy',
'Dark Humor',
'Dating Sim',
'Demons',
'Design & Illustration',
'Destruction',
'Detective',
'Difficult',
'Dinosaurs',
'Diplomacy',
'Documentary',
'Dog',
'Dragons',
'Drama',
'Driving',
'Dungeon Crawler',
'Dungeons & Dragons',
'Dynamic Narration',
'Dystopian',
'Early Access',
'Economy',
'Education',
'Emotional',
'Epic',
'Episodic',
'Experience',
'Experimental',
'Exploration',
'FMV',
'FPS',
'Faith',
'Family Friendly',
'Fantasy',
'Fast-Paced',
'Feature Film',
'Female Protagonist',
'Fighting',
'First-Person',
'Fishing',
'Flight',
'Football',
'Foreign',
'Free to Play',
'Funny',
'Futuristic',
'Gambling',
'Game Development',
'GameMaker',
'Games Workshop',
'Gaming',
'God Game',
'Golf',
'Gore',
'Gothic',
'Grand Strategy',
'Great Soundtrack',
'Grid-Based Movement',
'Gun Customization',
'Hack and Slash',
'Hacking',
'Hand-drawn',
'Hardware',
'Heist',
'Hex Grid',
'Hidden Object',
'Historical',
'Hockey',
'Horror',
'Horses',
'Hunting',
'Illuminati',
'Immersive Sim',
'Indie',
'Intentionally Awkward Controls',
'Interactive Fiction',
'Inventory Management',
'Investigation',
'Isometric',
'JRPG',
'Jet',
'Kickstarter',
'LEGO',
'Lara Croft',
'Lemmings',
'Level Editor',
'Linear',
'Local Co-Op',
'Local Multiplayer',
'Logic',
'Loot',
'Lore-Rich',
'Lovecraftian',
'MMORPG',
'MOBA',
'Magic',
'Management',
'Mars',
'Martial Arts',
'Massively Multiplayer',
'Masterpiece',
'Match 3',
'Mature',
'Mechs',
'Medieval',
'Memes',
'Metroidvania',
'Military',
'Mini Golf',
'Minigames',
'Minimalist',
'Mining',
'Mod',
'Moddable',
'Modern',
'Motocross',
'Motorbike',
'Mouse only',
'Movie',
'Multiplayer',
'Multiple Endings',
'Music',
'Music-Based Procedural Generation',
'Mystery',
'Mystery Dungeon',
'Mythology',
'NSFW',
'Narration',
'Nature',
'Naval',
'Ninja',
'Noir',
'Nonlinear',
'Nudity',
'Offroad',
'Old School',
'On-Rails Shooter',
'Online Co-Op',
'Open World',
'Otome',
'Parkour',
'Parody',
'Party-Based RPG',
'Perma Death',
'Philisophical',
'Photo Editing',
'Physics',
'Pinball',
'Pirates',
'Pixel Graphics',
'Platformer',
'Point & Click',
'Political',
'Politics',
'Pool',
'Post-apocalyptic',
'Procedural Generation',
'Programming',
'Psychedelic',
'Psychological',
'Psychological Horror',
'Puzzle',
'Puzzle-Platformer',
'PvE',
'PvP',
'Quick-Time Events',
'RPG',
'RPGMaker',
'RTS',
'Racing',
'Real Time Tactics',
'Real-Time',
'Real-Time with Pause',
'Realistic',
'Relaxing',
'Remake',
'Replay Value',
'Resource Management',
'Retro',
'Rhythm',
'Robots',
'Rogue-like',
'Rogue-lite',
'Romance',
'Rome',
'Runner',
'Sailing',
'Sandbox',
'Satire',
'Sci-fi',
'Science',
'Score Attack',
'Sequel',
'Sexual Content',
"Shoot 'Em Up",
'Shooter',
'Short',
'Side Scroller',
'Silent Protagonist',
'Simulation',
'Singleplayer',
'Skateboarding',
'Skating',
'Skiing',
'Sniper',
'Snow',
'Snowboarding',
'Soccer',
'Software',
'Software Training',
'Sokoban',
'Solitaire',
'Souls-like',
'Soundtrack',
'Space',
'Space Sim',
'Spectacle fighter',
'Spelling',
'Split Screen',
'Sports',
'Star Wars',
'Stealth',
'Steam Machine',
'Steampunk',
'Story Rich',
'Strategy',
'Strategy RPG',
'Stylized',
'Submarine',
'Superhero',
'Supernatural',
'Surreal',
'Survival',
'Survival Horror',
'Swordplay',
'Tactical',
'Tactical RPG',
'Tanks',
'Team-Based',
'Tennis',
'Text-Based',
'Third Person',
'Third-Person Shooter',
'Thriller',
'Time Attack',
'Time Management',
'Time Manipulation',
'Time Travel',
'Top-Down',
'Top-Down Shooter',
'Touch-Friendly',
'Tower Defense',
'TrackIR',
'Trading',
'Trading Card Game',
'Trains',
'Transhumanism',
'Transportation',
'Turn-Based',
'Turn-Based Combat',
'Turn-Based Strategy',
'Turn-Based Tactics',
'Tutorial',
'Twin Stick Shooter',
'Typing',
'Underground',
'Underwater',
'Unforgiving',
'Utilities',
'VR',
'Vampire',
'Video Production',
'Villain Protagonist',
'Violent',
'Visual Novel',
'Voice Control',
'Voxel',
'Walking Simulator',
'War',
'Wargame',
'Warhammer 40K',
'Web Publishing',
'Werewolves',
'Western',
'Word Game',
'World War I',
'World War II',
'Wrestling',
'Zombies',
'e-sports'];

export const FilterSettingsPopularTags = (props: IFilterSettingTypeProp) => {
    const [error, setError] = useState<string>("");
    const [tagList, setTagList] = useState<string[]>([]);

    const addTag = (t: string[]) => {
        setTagList(t);
    }

    const addFilter = () => {
        if (tagList.length === 0) {
            setError("Please select a tag to filter");
            return;
        }

        setError("");

        props.setFilterData({
            type: "PopularTags",
            data: tagList,
            visualData: (tagList.length > 3) ? `${tagList.slice(0,3).join(", ")}, ...` : tagList.join(", ")
        })
    }

    const handleInput = (e: React.SyntheticEvent, value: string[]) => {
        if (value !== null) {
            addTag(value);
        }
    };

    return (
       <FormControl sx={{ width: 1, height: 200 }}>
            <Autocomplete
                multiple
                id="popularTags1"
                options={tags}
                onChange={handleInput}
                getOptionLabel={(option) => option}
                renderInput={(params) => (
                    <TextField {...params} InputProps={{...params.InputProps, type: 'search'}} label="Tags" placeholder="Tag" />
                )}
            />
            <Button onClick={addFilter}>Add filter</Button>
            <Alert severity='error' sx={{display: (error === "") ? 'none' : 'inherit'}}>{error}</Alert>
       </FormControl> 
    )
}